POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Seu nome1",
  "email": "SeuEmail1@gmail.com", 
  "referrer": ""
}
// Primeira inscrição deixa vazio o 'referrer'

// A partir da primeira inscrição, você vai receber um subscriberId, coloque ele dentro do "referrer" e no lugar do "subscriberId" nas rotas seguintes e pronto.

# Quantas vezes clicaram no link que você enviou
### 
GET http://localhost:3333/subscribers/subscriberId/ranking/clicks


// Link de envio para seu amigo clicar e se inscrever no evento
### 
GET http://localhost:3333/invites/subscriberId


// Quantas pessoas se inscreveram a partir do seu link
###
GET http://localhost:3333/subscribers/subscriberId/ranking/count


// Qual posição no ranking você está 
###
GET http://localhost:3333/subscribers/subscriberId/ranking/position
  

// Mostra o ranking geral
### 
GET http://localhost:3333/ranking